Fixes indentation
Fixed indentation in startup script

diff --git a/templates/haproxy.debian-multi.init.j2 b/templates/haproxy.debian-multi.init.j2
--- a/templates/haproxy.debian-multi.init.j2
+++ b/templates/haproxy.debian-multi.init.j2
@@ -24,7 +24,7 @@ test -f "$CONFIG" || exit 0
 test -d "$CONFIG_D" || exit 0
 
 if [ -e /etc/default/haproxy ]; then
-	. /etc/default/haproxy
+  . /etc/default/haproxy
 fi
 
 test "$ENABLED" != "0" || exit 0
@@ -34,167 +34,167 @@ test "$ENABLED" != "0" || exit 0
 
 haproxy_config()
 {
-	config="-f $CONFIG"
-	i=1
-	for cfgfile in `find $CONFIG_D -type f -name '*.cfg'|sort -n`;
-	do
-		config="$config -f $cfgfile"
-	done
-	return 0
+  config="-f $CONFIG"
+  i=1
+  for cfgfile in `find $CONFIG_D -type f -name '*.cfg'|sort -n`;
+  do
+    config="$config -f $cfgfile"
+  done
+  return 0
 }
 
 haprox_check()
 {
-	haproxy_config || return 2
+  haproxy_config || return 2
   /usr/sbin/haproxy -c -- $config
   return $?
 }
 
 haproxy_start()
 {
-	haproxy_config || return 2
-	start-stop-daemon --start --pidfile "$PIDFILE" \
-		--exec $HAPROXY -- $config -D -p "$PIDFILE" \
-		$EXTRAOPTS || return 2
-	return 0
+  haproxy_config || return 2
+  start-stop-daemon --start --pidfile "$PIDFILE" \
+    --exec $HAPROXY -- $config -D -p "$PIDFILE" \
+    $EXTRAOPTS || return 2
+  return 0
 }
 
 haproxy_stop()
 {
-	if [ ! -f $PIDFILE ] ; then
-		# This is a success according to LSB
-		return 0
-	fi
-	for pid in $(cat $PIDFILE) ; do
-		/bin/kill $pid || return 4
-	done
-	rm -f $PIDFILE
-	return 0
+  if [ ! -f $PIDFILE ] ; then
+    # This is a success according to LSB
+    return 0
+  fi
+  for pid in $(cat $PIDFILE) ; do
+    /bin/kill $pid || return 4
+  done
+  rm -f $PIDFILE
+  return 0
 }
 
 haproxy_reload()
 {
-	haproxy_config || return 2
-	$HAPROXY $config -p $PIDFILE -D $EXTRAOPTS -sf $(cat $PIDFILE) \
-		|| return 2
-	return 0
+  haproxy_config || return 2
+  $HAPROXY $config -p $PIDFILE -D $EXTRAOPTS -sf $(cat $PIDFILE) \
+    || return 2
+  return 0
 }
 
 haproxy_status()
 {
-	if [ ! -f $PIDFILE ] ; then
-		# program not running
-		return 3
-	fi
+  if [ ! -f $PIDFILE ] ; then
+    # program not running
+    return 3
+  fi
 
-	for pid in $(cat $PIDFILE) ; do
-		if ! ps --no-headers p "$pid" | grep haproxy > /dev/null ; then
-			# program running, bogus pidfile
-			return 1
-		fi
-	done
+  for pid in $(cat $PIDFILE) ; do
+    if ! ps --no-headers p "$pid" | grep haproxy > /dev/null ; then
+      # program running, bogus pidfile
+      return 1
+    fi
+  done
 
-	return 0
+  return 0
 }
 
 
 case "$1" in
 check)
-	log_daemon_msg "Checking haproxy config" "haproxy"
-	haproxy_check
-	ret=$?
-	case "$ret" in
-	0)
-		log_end_msg 0
+  log_daemon_msg "Checking haproxy config" "haproxy"
+  haproxy_check
+  ret=$?
+  case "$ret" in
+  0)
+    log_end_msg 0
     echo "config ok"
-		;;
-	*)
-		log_end_msg $ret
-		echo "config seems invalid"
-		;;
-	esac
-	exit $ret
-	;;
+    ;;
+  *)
+    log_end_msg $ret
+    echo "config seems invalid"
+    ;;
+  esac
+  exit $ret
+  ;;
 start)
-	log_daemon_msg "Starting haproxy" "haproxy"
-	haproxy_start
-	ret=$?
-	case "$ret" in
-	0)
-		log_end_msg 0
-		;;
-	1)
-		log_end_msg 1
-		echo "pid file '$PIDFILE' found, haproxy not started."
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
-	;;
+  log_daemon_msg "Starting haproxy" "haproxy"
+  haproxy_start
+  ret=$?
+  case "$ret" in
+  0)
+    log_end_msg 0
+    ;;
+  1)
+    log_end_msg 1
+    echo "pid file '$PIDFILE' found, haproxy not started."
+    ;;
+  2)
+    log_end_msg 1
+    ;;
+  esac
+  exit $ret
+  ;;
 stop)
-	log_daemon_msg "Stopping haproxy" "haproxy"
-	haproxy_stop
-	ret=$?
-	case "$ret" in
-	0|1)
-		log_end_msg 0
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
-	;;
+  log_daemon_msg "Stopping haproxy" "haproxy"
+  haproxy_stop
+  ret=$?
+  case "$ret" in
+  0|1)
+    log_end_msg 0
+    ;;
+  2)
+    log_end_msg 1
+    ;;
+  esac
+  exit $ret
+  ;;
 reload|force-reload)
-	log_daemon_msg "Reloading haproxy" "haproxy"
-	haproxy_reload
-	case "$?" in
-	0|1)
-		log_end_msg 0
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	;;
+  log_daemon_msg "Reloading haproxy" "haproxy"
+  haproxy_reload
+  case "$?" in
+  0|1)
+    log_end_msg 0
+    ;;
+  2)
+    log_end_msg 1
+    ;;
+  esac
+  ;;
 restart)
-	log_daemon_msg "Restarting haproxy" "haproxy"
-	haproxy_stop
-	haproxy_start
-	case "$?" in
-	0)
-		log_end_msg 0
-		;;
-	1)
-		log_end_msg 1
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	;;
+  log_daemon_msg "Restarting haproxy" "haproxy"
+  haproxy_stop
+  haproxy_start
+  case "$?" in
+  0)
+    log_end_msg 0
+    ;;
+  1)
+    log_end_msg 1
+    ;;
+  2)
+    log_end_msg 1
+    ;;
+  esac
+  ;;
 status)
-	haproxy_status
-	ret=$?
-	case "$ret" in
-	0)
-		echo "haproxy is running."
-		;;
-	1)
-		echo "haproxy dead, but $PIDFILE exists."
-		;;
-	*)
-		echo "haproxy not running."
-		;;
-	esac
-	exit $ret
-	;;
+  haproxy_status
+  ret=$?
+  case "$ret" in
+  0)
+    echo "haproxy is running."
+    ;;
+  1)
+    echo "haproxy dead, but $PIDFILE exists."
+    ;;
+  *)
+    echo "haproxy not running."
+    ;;
+  esac
+  exit $ret
+  ;;
 *)
-	echo "Usage: /etc/init.d/haproxy {start|stop|reload|restart|status}"
-	exit 2
-	;;
+  echo "Usage: /etc/init.d/haproxy {start|stop|reload|restart|status}"
+  exit 2
+  ;;
 esac
 
 :
